### ISSUE TITLE
numba cuda error

### ISSUE THREAD

**Issue by shansongliu** [yandili/forge_load#2]
在运行gpu_load的main.py时，在运行了一段时间后，会出现下面这种错误:
Traceback (most recent call last):
    File "main.py", line 136, in <module>
        Worker.main(target)
    File "main.py", line 124, in main
        worker.run_awhile(10)
    File "main.py", line 81, in run_awhile
        self.my_kernel[int(self.multiplier * self.blockspergrid), self.threadsperblock](self._device_data)
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/compiler.py, line 729, in __call__
        return self.dispatcher.call(args, self.griddim, self.blockdim,
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/compiler.py, line 919, in call
        kernel.launch(args, griddim, blockdim, stream, sharedmem)
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/compiler.py, line 576, in launch
        driver.launch_kernel(cufunc.handle,
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2550, in launch_kernel
        driver.cuLaunchKernel(cufunc_handle,
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 319, in safe_cuda_api_call
        self._check_ctypes_error(fname, retcode)
    File "/data/miniconda3/envs/pt17/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 387, in _check_ctypes_error
        raise CudaAPIError(retcode, msg)
    numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuLaunchKernel results in UNKNOWN_CUDA_ERROR

请问是什么原因呢

**Comment by yandili** [comment]
可能需要排查一下运行环境问题，我试验了一下各个包的新版本，配置如下
- Python==3.7.10
- CUDA==10.1
- numpy==1.18.5
- numba==0.55.1
- GPUtil==1.4.0

运行是正常的，会打印日志，观察了十分钟左右，没有见到异常。Docker版本也没有看到过类似日志。
```
(cuda10.1) $ python main.py 
threadsperblock: 128, blockspergrid: 4
Monitor started: True
Initial average load 42.2
Idle for 5s with load 74.0
Idle for 5s with load 75.0
Idle for 5s with load 75.0
Idle for 5s with load 76.0
Run for 10s with load 0.0 and multiplier 1000
Adjusted speed: slow_down
Idle for 5s with load 75.0
Idle for 5s with load 75.0
```
